version: '3'  

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - ./node_modules/:/home/node/app/node_modules/
    networks:
      - app-network
    command: >
      sh -c "npm install && npx prisma generate && ./wait-for.sh mysql:3306 -- /home/node/app/node_modules/.bin/nodemon app.js
      && node app.js"

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    env_file: .env
    environment:
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8001:80
    restart: unless-stopped
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  dbdata: