FROM mysql:8.0.20

# If running into problems logging into PHPMyAdmin, uncomment below line and rebuild
# (see https://stackoverflow.com/a/50437307/6010889)
RUN echo "default_authentication_plugin=mysql_native_password" >> /etc/mysql/my.cnf